// DISCLAIMER: Technical demo code — legal wrappers required in production
// SPDX-License-Identifier: MIT
//
//! Groth16 ZK-KYC proof generation using ark-groth16.
//! Generates zero-knowledge proofs that an address is in the approved KYC set
//! without revealing the address itself.
//!
//! Target: proof generation <200ms

use ark_bn254::{Bn254, Fr};
use ark_ff::PrimeField;
use ark_groth16::{Groth16, ProvingKey};
use ark_serialize::{CanonicalDeserialize, CanonicalSerialize};
use ark_snark::SNARK;
use rand::rngs::OsRng;
use thiserror::Error;
use tracing::info;

use crate::LOG_PREFIX;
use zk_circuits::kyc_circuit::{
    build_merkle_tree, native_leaf_hash, native_nullifier, KycCircuit, RecursiveKycCircuit,
};

#[derive(Error, Debug)]
pub enum ProverError {
    #[error("[K-RWA] Proof generation failed: {0}")]
    ProofGenFailed(String),
    #[error("[K-RWA] Setup not initialized: {0}")]
    SetupNotInitialized(String),
    #[error("[K-RWA] IO error: {0}")]
    IoError(#[from] std::io::Error),
}

/// Groth16 proof for ZK-KYC verification
#[derive(Debug, Clone)]
pub struct ZkProof {
    /// Serialized Groth16 proof (A, B, C curve points)
    pub proof_bytes: Vec<u8>,
    /// Public inputs: [merkle_root, nullifier_hash] as field element bytes
    pub public_inputs: Vec<Vec<u8>>,
    /// Proof hash for on-chain commitment (sha256 of proof_bytes)
    pub proof_hash: [u8; 32],
}

/// ZK-KYC witness (private inputs for the prover)
pub struct ZkWitness {
    /// Secret key (field element bytes)
    pub secret_key: Vec<u8>,
    /// Index of the prover's leaf in the Merkle tree
    pub leaf_index: usize,
    /// All approved leaves in the Merkle tree
    pub all_leaves: Vec<Vec<u8>>,
}

/// Groth16 ZK-KYC prover
pub struct ZkProver {
    /// Deserialized proving key
    proving_key: Option<ProvingKey<Bn254>>,
    /// Deserialized recursive proving key
    recursive_proving_key: Option<ProvingKey<Bn254>>,
    /// Tree depth for the circuit
    tree_depth: usize,
}

impl ZkProver {
    /// Create a new ZK prover with specified tree depth
    pub fn new(tree_depth: usize) -> Self {
        info!(
            "{} Initializing ZK-KYC prover (Groth16/BN254, depth={})",
            LOG_PREFIX, tree_depth
        );
        Self {
            proving_key: None,
            recursive_proving_key: None,
            tree_depth,
        }
    }

    /// Load proving key from file (generated by trusted setup)
    pub fn load_proving_key(&mut self, path: &str) -> Result<(), ProverError> {
        info!("{} Loading proving key from: {}", LOG_PREFIX, path);
        let key_bytes = std::fs::read(path)?;
        let pk = ProvingKey::<Bn254>::deserialize_compressed(&key_bytes[..])
            .map_err(|e| ProverError::SetupNotInitialized(format!("deserialization: {}", e)))?;
        self.proving_key = Some(pk);
        info!("{} Proving key loaded successfully", LOG_PREFIX);
        Ok(())
    }

    /// Set proving key directly (from in-memory setup)
    pub fn set_proving_key(&mut self, pk: ProvingKey<Bn254>) {
        self.proving_key = Some(pk);
    }

    /// Set recursive proving key directly (from in-memory setup)
    pub fn set_recursive_proving_key(&mut self, pk: ProvingKey<Bn254>) {
        self.recursive_proving_key = Some(pk);
    }

    /// Load recursive proving key from file (generated by recursive trusted setup)
    pub fn load_recursive_proving_key(&mut self, path: &str) -> Result<(), ProverError> {
        info!("{} Loading recursive proving key from: {}", LOG_PREFIX, path);
        let key_bytes = std::fs::read(path)?;
        let pk = ProvingKey::<Bn254>::deserialize_compressed(&key_bytes[..])
            .map_err(|e| ProverError::SetupNotInitialized(format!("deserialization: {}", e)))?;
        self.recursive_proving_key = Some(pk);
        info!("{} Recursive proving key loaded successfully", LOG_PREFIX);
        Ok(())
    }

    /// Generate a Groth16 proof for ZK-KYC
    ///
    /// Proves: "I know a secret whose hash is a leaf in the Merkle tree
    /// with the given root, without revealing the secret or leaf position."
    ///
    /// Target: <200ms
    pub fn generate_proof(&self, witness: &ZkWitness) -> Result<ZkProof, ProverError> {
        info!("{} Generating Groth16 ZK-KYC proof", LOG_PREFIX);

        let pk = self.proving_key.as_ref().ok_or_else(|| {
            ProverError::SetupNotInitialized("Proving key not loaded. Run trusted setup first.".into())
        })?;

        let start = std::time::Instant::now();

        // Convert witness bytes to field elements
        let secret = Fr::from_le_bytes_mod_order(&witness.secret_key);

        // Build leaf hashes from all approved addresses
        let leaves: Vec<Fr> = witness
            .all_leaves
            .iter()
            .map(|leaf_bytes| Fr::from_le_bytes_mod_order(leaf_bytes))
            .collect();

        // Compute the prover's leaf hash
        let _prover_leaf = native_leaf_hash(secret);

        // Build Merkle tree and get path for the target leaf
        let (root, path, indices) = build_merkle_tree(&leaves, witness.leaf_index);

        // Compute nullifier
        let nullifier = native_nullifier(secret);

        // Create the circuit with witness
        let circuit = KycCircuit::new_with_witness(
            root,
            nullifier,
            secret,
            path,
            indices,
            self.tree_depth,
        );

        // Generate Groth16 proof
        // Cryptographically secure RNG for proof generation
        let mut rng = OsRng;
        let proof = Groth16::<Bn254>::prove(pk, circuit, &mut rng)
            .map_err(|e: ark_relations::r1cs::SynthesisError| ProverError::ProofGenFailed(e.to_string()))?;

        // Serialize proof
        let mut proof_bytes = Vec::new();
        proof
            .serialize_compressed(&mut proof_bytes)
            .map_err(|e| ProverError::ProofGenFailed(format!("proof serialization: {}", e)))?;

        // Compute proof hash for on-chain commitment
        use sha2::{Digest, Sha256};
        let proof_hash: [u8; 32] = Sha256::digest(&proof_bytes).into();

        // Serialize public inputs
        let mut root_bytes = Vec::new();
        ark_serialize::CanonicalSerialize::serialize_compressed(&root, &mut root_bytes)
            .map_err(|e| ProverError::ProofGenFailed(format!("root serialization: {}", e)))?;
        let mut nullifier_bytes = Vec::new();
        ark_serialize::CanonicalSerialize::serialize_compressed(&nullifier, &mut nullifier_bytes)
            .map_err(|e| ProverError::ProofGenFailed(format!("nullifier serialization: {}", e)))?;

        let elapsed = start.elapsed();
        info!(
            "{} ZK proof generated in {:?} (proof={} bytes, hash={})",
            LOG_PREFIX,
            elapsed,
            proof_bytes.len(),
            hex::encode(proof_hash)
        );

        Ok(ZkProof {
            proof_bytes,
            public_inputs: vec![root_bytes, nullifier_bytes],
            proof_hash,
        })
    }

    /// Generate a recursive ZK proof (proof-chain pattern).
    ///
    /// If `previous_proof` is `Some`, verifies it first using the provided verifier,
    /// then includes its validity as a witness. The circuit enforces that chained
    /// proofs (chain_depth > 0) must have a valid previous proof.
    ///
    /// Returns a `ZkProof` with 4 public inputs:
    /// [merkle_root, nullifier_hash, previous_merkle_root, chain_depth]
    pub fn generate_recursive_proof(
        &self,
        witness: &ZkWitness,
        previous_proof: Option<&ZkProof>,
        chain_depth: u64,
    ) -> Result<ZkProof, ProverError> {
        info!(
            "{} Generating recursive Groth16 ZK-KYC proof (chain_depth={})",
            LOG_PREFIX, chain_depth
        );

        let pk = self.recursive_proving_key.as_ref().ok_or_else(|| {
            ProverError::SetupNotInitialized(
                "Recursive proving key not loaded. Run recursive trusted setup first.".into(),
            )
        })?;

        let start = std::time::Instant::now();

        // Convert witness bytes to field elements
        let secret = Fr::from_le_bytes_mod_order(&witness.secret_key);

        // Build leaf hashes from all approved addresses
        let leaves: Vec<Fr> = witness
            .all_leaves
            .iter()
            .map(|leaf_bytes| Fr::from_le_bytes_mod_order(leaf_bytes))
            .collect();

        // Build Merkle tree and get path for the target leaf
        let (root, path, indices) = build_merkle_tree(&leaves, witness.leaf_index);

        // Compute nullifier
        let nullifier = native_nullifier(secret);

        // Determine previous proof validity and root
        let (previous_proof_valid, previous_merkle_root) = if chain_depth > 0 {
            let prev = previous_proof.ok_or_else(|| {
                ProverError::ProofGenFailed(
                    "chain_depth > 0 but no previous proof provided".into(),
                )
            })?;

            // Extract previous merkle root from previous proof's public inputs
            let prev_root = if !prev.public_inputs.is_empty() {
                Fr::from_le_bytes_mod_order(&prev.public_inputs[0])
            } else {
                Fr::from(0u64)
            };

            // The caller is responsible for verifying the previous proof off-chain.
            // We assume it is valid if it was passed in.
            (true, prev_root)
        } else {
            (false, Fr::from(0u64))
        };

        // Build the recursive circuit
        let circuit = if chain_depth == 0 {
            RecursiveKycCircuit::new_first_proof(
                root, nullifier, secret, path, indices, self.tree_depth,
            )
        } else {
            RecursiveKycCircuit::new_chained_proof(
                root,
                nullifier,
                secret,
                path,
                indices,
                self.tree_depth,
                previous_proof_valid,
                previous_merkle_root,
                Fr::from(chain_depth),
            )
        };

        // Generate Groth16 proof
        // Cryptographically secure RNG for proof generation
        let mut rng = OsRng;
        let proof = Groth16::<Bn254>::prove(pk, circuit, &mut rng)
            .map_err(|e: ark_relations::r1cs::SynthesisError| {
                ProverError::ProofGenFailed(e.to_string())
            })?;

        // Serialize proof
        let mut proof_bytes = Vec::new();
        proof
            .serialize_compressed(&mut proof_bytes)
            .map_err(|e| ProverError::ProofGenFailed(format!("proof serialization: {}", e)))?;

        // Compute proof hash for on-chain commitment
        use sha2::{Digest, Sha256};
        let proof_hash: [u8; 32] = Sha256::digest(&proof_bytes).into();

        // Serialize public inputs: [merkle_root, nullifier_hash, previous_merkle_root, chain_depth]
        let chain_depth_field = Fr::from(chain_depth);
        let public_input_fields = [root, nullifier, previous_merkle_root, chain_depth_field];
        let public_inputs: Vec<Vec<u8>> = public_input_fields
            .iter()
            .map(|f| {
                let mut bytes = Vec::new();
                ark_serialize::CanonicalSerialize::serialize_compressed(f, &mut bytes)
                    .expect("field serialization should not fail");
                bytes
            })
            .collect();

        let elapsed = start.elapsed();
        info!(
            "{} Recursive ZK proof generated in {:?} (chain_depth={}, proof={} bytes, hash={})",
            LOG_PREFIX,
            elapsed,
            chain_depth,
            proof_bytes.len(),
            hex::encode(proof_hash)
        );

        Ok(ZkProof {
            proof_bytes,
            public_inputs,
            proof_hash,
        })
    }
}

impl Default for ZkProver {
    fn default() -> Self {
        Self::new(2)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use zk_circuits::kyc_circuit::native_leaf_hash;
    use zk_circuits::setup::run_trusted_setup;

    #[test]
    fn test_proof_generation() {
        // Run trusted setup
        let keys_dir = "/tmp/assetmint_prover_test";
        let _ = std::fs::remove_dir_all(keys_dir);
        let setup = run_trusted_setup(2, keys_dir).expect("setup should succeed");

        // Create prover
        let mut prover = ZkProver::new(2);
        prover.set_proving_key(setup.proving_key);

        // Create witness: secret=42, leaf index=1, 4 leaves
        let secret = Fr::from(42u64);
        let leaf = native_leaf_hash(secret);
        let leaves = vec![Fr::from(100u64), leaf, Fr::from(200u64), Fr::from(300u64)];

        let witness = ZkWitness {
            secret_key: {
                let mut bytes = Vec::new();
                ark_serialize::CanonicalSerialize::serialize_compressed(&secret, &mut bytes).unwrap();
                bytes
            },
            leaf_index: 1,
            all_leaves: leaves
                .iter()
                .map(|l| {
                    let mut bytes = Vec::new();
                    ark_serialize::CanonicalSerialize::serialize_compressed(l, &mut bytes).unwrap();
                    bytes
                })
                .collect(),
        };

        let proof = prover.generate_proof(&witness);
        assert!(proof.is_ok(), "Proof generation should succeed");
        let proof = proof.unwrap();
        assert!(!proof.proof_bytes.is_empty(), "Proof should not be empty");
        assert_eq!(proof.public_inputs.len(), 2, "Should have 2 public inputs");

        // Clean up
        let _ = std::fs::remove_dir_all(keys_dir);
    }
}
