// DISCLAIMER: Technical demo code — legal wrappers required in production
// SPDX-License-Identifier: MIT
//
//! Groth16 ZK-KYC proof generation using ark-groth16.
//! Generates zero-knowledge proofs that an address is in the approved KYC set
//! without revealing the address itself.
//!
//! Target: proof generation <200ms

use thiserror::Error;
use tracing::info;

use crate::LOG_PREFIX;

#[derive(Error, Debug)]
pub enum ProverError {
    #[error("[K-RWA] Proof generation failed: {0}")]
    ProofGenFailed(String),
    #[error("[K-RWA] Setup not initialized: {0}")]
    SetupNotInitialized(String),
}

/// Groth16 proof for ZK-KYC verification
#[derive(Debug, Clone)]
pub struct ZkProof {
    /// Serialized proof bytes (A, B, C points)
    pub proof_bytes: Vec<u8>,
    /// Public inputs: [merkle_root, nullifier_hash]
    pub public_inputs: Vec<Vec<u8>>,
}

/// ZK-KYC witness (private inputs)
pub struct ZkWitness {
    /// Private key of the prover
    pub private_key: Vec<u8>,
    /// Merkle path from leaf to root
    pub merkle_path: Vec<Vec<u8>>,
    /// Leaf index in the Merkle tree
    pub leaf_index: u64,
}

/// Groth16 ZK-KYC prover
pub struct ZkProver {
    /// Proving key bytes (loaded from trusted setup)
    proving_key: Option<Vec<u8>>,
}

impl ZkProver {
    /// Create a new ZK prover
    pub fn new() -> Self {
        info!("{} Initializing ZK-KYC prover (Groth16/BN254)", LOG_PREFIX);
        Self { proving_key: None }
    }

    /// Load proving key from file (generated by trusted setup)
    pub fn load_proving_key(&mut self, path: &str) -> Result<(), ProverError> {
        info!("{} Loading proving key from: {}", LOG_PREFIX, path);
        // TODO: Load serialized ProvingKey<Bn254> from file
        // Uses ark-serialize for deserialization
        let key_bytes = std::fs::read(path)
            .map_err(|e| ProverError::SetupNotInitialized(format!("{}: {}", path, e)))?;
        self.proving_key = Some(key_bytes);
        Ok(())
    }

    /// Generate a Groth16 proof for ZK-KYC
    ///
    /// Proves: "I know a private key whose public key hash is in the
    /// Merkle tree with the given root, without revealing the key or leaf."
    ///
    /// Target: <200ms
    pub fn generate_proof(
        &self,
        _witness: &ZkWitness,
        merkle_root: &[u8; 32],
    ) -> Result<ZkProof, ProverError> {
        info!("{} Generating Groth16 ZK-KYC proof", LOG_PREFIX);

        if self.proving_key.is_none() {
            return Err(ProverError::SetupNotInitialized(
                "Proving key not loaded. Run trusted setup first.".into(),
            ));
        }

        let start = std::time::Instant::now();

        // TODO: Implement actual Groth16 proving:
        // 1. Create KycCircuit instance with witness
        // 2. Generate proof using ark-groth16::Groth16::<Bn254>::prove()
        // 3. Serialize proof and public inputs

        let elapsed = start.elapsed();
        info!("{} ZK proof generated in {:?}", LOG_PREFIX, elapsed);

        Ok(ZkProof {
            proof_bytes: vec![],
            public_inputs: vec![merkle_root.to_vec()],
        })
    }
}

impl Default for ZkProver {
    fn default() -> Self {
        Self::new()
    }
}
